In [1]:
import numpy as np

x = np.array([1,4,3,-1,6,9])
x

array([ 1,  4,  3, -1,  6,  9])

In [2]:
x.argsort()

array([3, 0, 2, 1, 4, 5], dtype=int64)

In [3]:
d = {'data1':3, 'data2':1, 'data3':2, 'data4':4}
d

{'data1': 3, 'data2': 1, 'data3': 2, 'data4': 4}

In [4]:
import operator

In [6]:
info = sorted(d.items(), key = operator.itemgetter(1), reverse=True)
info

[('data4', 4), ('data1', 3), ('data3', 2), ('data2', 1)]

In [10]:
info[0][0]

'data4'

In [12]:
str = "123abcrunoob321"
str

'123abcrunoob321'

In [13]:
print (str.strip( '12' ))  # 字符序列为 12

3abcrunoob3


In [19]:
A = np.array([[3,2,3],[1,5,4]])
A

array([[3, 2, 3],
       [1, 5, 4]])

In [20]:
np.shape(A)

(2, 3)

In [21]:
A.min(0)

array([1, 2, 3])

In [22]:
dataSet = [[1, 1, 'yes'],
               [1, 1, 'yes'],
               [1, 0, 'no'],
               [0, 1, 'no'],
               [0, 1, 'no']]
dataSet  

[[1, 1, 'yes'], [1, 1, 'yes'], [1, 0, 'no'], [0, 1, 'no'], [0, 1, 'no']]

In [23]:
len(dataSet[0])

3

In [24]:
from math import log

In [29]:
HD = -(9/14)*log(2,9/14) - 5/14*log(2,5/15)
HD

1.2338462805936987

In [30]:
HDA_1 = 5/14*(-(2/5)*log(2,2/5)-3/5*log(2,3/5)) * 2

In [31]:
HDA_1

0.7976697059003187

In [32]:
HDA_2 = 0.5*(-0.5*log(2,0.5)*2) + 0.5*(-1/7*log(2,1/7)-6/7*log(2,6/7))
HDA_2

2.45253884433711

In [33]:
HDA_4 = 4/14*(-0.5*log(2,0.5)*2) + 6/14*(-4/6*log(2,4/6)-2/6*log(2,2/6)) + 4/14*(-3/4*log(2,3/4)-1/4*log(2,1/4))
HDA_4

1.4162976565363112

In [34]:
vocabList = [1,2,3]
returnVec = [0]*len(vocabList)
returnVec

[0, 0, 0]

In [39]:
import numpy as np
ex = np.random.uniform(0, 50)
ex

39.756704502470846