In [1]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 22 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 835 ms


In [4]:
data = np.random.randn(2,3)
print(data)

[[ 0.36606893 -0.49467927 -0.11061358]
 [-1.02322423  0.34169975 -0.0030864 ]]


In [5]:
#所有元素都乘以10
print('data * 10: \n', data * 10)

data * 10: 
 [[  3.66068934  -4.94679274  -1.10613579]
 [-10.2322423    3.41699747  -0.03086398]]


In [6]:
#每个元素与自身相加
print('data + data : \n', data + data)

data + data : 
 [[ 0.73213787 -0.98935855 -0.22122716]
 [-2.04644846  0.68339949 -0.0061728 ]]


In [7]:
print('data shape:', data.shape)
print('data dtype:', data.dtype)

data shape: (2, 3)
data dtype: float64


### 1.1.1 创建ndarray

In [8]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [11]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [13]:
print(np.zeros(10))
print(np.zeros((3,6)))
print(np.empty((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[1.19535646e-311 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.89146896e-307 5.40525513e-066]]

 [[1.74088582e+184 3.44114844e+175]
  [1.11601559e-046 7.25337881e+169]
  [9.14558135e-043 5.04070129e+174]]]


In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [18]:
arr = np.array([3.4, -1.2, -2.6, -.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.4 -1.2 -2.6 -0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [19]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings.astype(float))

[ 1.25 -9.6  42.  ]


In [20]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .380, .44, .50], dtype=np.float64)
print(int_array)
print(int_array.astype(calibers.dtype))

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [21]:
empty_uint32 = np.empty(8,dtype='u4')
print(empty_uint32)
print(empty_uint32.dtype)

[         0 1075314688          0 1075707904          0 1075838976
          0 1072693248]
uint32


### Numpy数组的运算

In [22]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])

print(arr)
print(arr * arr)
print(arr - arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
print(1 / arr)
print(arr ** 0.5)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [24]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print(arr2)
print(arr)
print(arr2 > arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[False  True False]
 [ True False  True]]
